name: elearning_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/accounting.jpg
    - assets/app 1.png
    - assets/app.png
    - assets/app111.png
    - assets/design.jpg
    - assets/laptop.jpg
    - assets/marketing.png
    - assets/photography.jpg
    - assets/web_development.png
